---
# install nginx

  - name: Install Nginx on Ubuntu
    apt:
      name: nginx
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Install Nginx on CentOS
    dnf:
      name: epel-release, nginx
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"

